# docker-compose.yml (Fixed Version)

services:
  agent-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: property-scout-agent-image
    container_name: agent-runner
    env_file:
      - .env
    environment:
      - MCP_HOSTNAME=docker
    depends_on:
      - immoscout-server
      - serpapi-server
      - copernicus-server
      - inspire-server
    volumes:
      - ./evaluations:/app/dist/evaluations
    command: "node dist/index.js"
    ports:
      - "3000:3000"
    networks:
      - agent-network

  immoscout-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: property-scout-agent-image
    container_name: immoscout-server
    env_file:
      - .env
    environment:
      - MCP_HOSTNAME=docker
    command: "node dist/mcp/servers/immoscout-server.js"
    ports:
      - "3001:3001"
    networks:
      - agent-network

  serpapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: property-scout-agent-image
    container_name: serpapi-server
    env_file:
      - .env
    environment:
      - MCP_HOSTNAME=docker
    command: "node dist/mcp/servers/serpapi-server.js"
    ports:
      - "3002:3002"
    networks:
      - agent-network

  copernicus-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: property-scout-agent-image
    container_name: copernicus-server
    env_file:
      - .env
    environment:
      - MCP_HOSTNAME=docker
    command: "node dist/mcp/servers/copernicus-server.js"
    ports:
      - "3003:3003"
    networks:
      - agent-network

  inspire-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: property-scout-agent-image
    container_name: inspire-server
    env_file:
      - .env
    environment:
      - MCP_HOSTNAME=docker
    command: "node dist/mcp/servers/inspire-server.js"
    ports:
      - "3004:3004"
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge