# docker-compose.yml
services:
  agent-runner:
    build: .
    container_name: agent-runner
    depends_on:
      - immoscout-server
      - serpapi-server
      - copernicus-server
      - inspire-server
    # This block passes the .env file variables into the container
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT_IMMOSCOUT=3001
      - PORT_SERPAPI=3002
      - PORT_COPERNUCUS=3003
      - PORT_INSPIRE=3004
    volumes:
      - ./evaluations:/app/dist/evaluations
    command: "node dist/index.js"

  immoscout-server:
    build: .
    container_name: immoscout-server
    # FIX: Add the environment block here
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: "node dist/mcp/servers/immoscout-server.js"

  serpapi-server:
    build: .
    container_name: serpapi-server
    # FIX: Add the environment block here
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: "node dist/mcp/servers/serpapi-server.js"

  copernicus-server:
    build: .
    container_name: copernicus-server
    # FIX: Add the environment block here
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: "node dist/mcp/servers/copernicus-server.js"

  inspire-server:
    build: .
    container_name: inspire-server
    # FIX: Add the environment block here
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: "node dist/mcp/servers/inspire-server.js"